#!/bin/sh
#
# This endpoint shows all the counters.
#

set -eu
datadir=/var/lib/lpil
database="$datadir/counters.sqlite"

printf "status: 200 Ok\n"
printf "content-type: application/json\n"
printf "\n"

# Query the counters and build JSON in the hackiest way possible.
# I need to figure out a better way to do this.

printf "{"

sqlite3 "$database" <<SQL | sed '$s/,$//'
.mode list

select
  '"' || name || '":' || json_group_object(date, count) || ','
from (
  select name, date, count
  from counters
  order by name asc, date desc
)
group by
  name
SQL

printf "}"

exit 0
