#!/bin/sh
#
# This endpoint shows all the counters.
#

set -eu
datadir=/var/lib/lpil
database="$datadir/counters.sqlite"

printf "status: 200 Ok\n"
printf "content-type: application/json\n"
printf "\n"

printf "{"

sqlite3 "$database" <<SQL | sed '$s/,$//'
.mode list

select
  '"' ||  name || '":' ||
    json_group_array(json_object('date', date, 'count', count))
  || ','
from (
  select name, date, count
  from counters
  order by name asc, date desc
)
group by
  name
SQL

printf "}"

exit 0
