# Serve the tailscale network interface only
interface=tailscale0
bind-interfaces

# DNS4EU's unfiltered resolver
server=86.54.11.100
server=86.54.11.200

# slowbro.lpil.uk and all its subdomains
address=/slowbro.lpil.uk/100.68.222.85 
