music_directory	"/music"
playlist_directory "/playlists"

db_file	"/data/database"
state_file "/data/state"
sticker_file "/data/sticker.sql"

user "mpd"
group "nogroup"

bind_to_address "0.0.0.0"
port "6600"

restore_paused "yes"
metadata_to_use	"artist,album,title,track,name,genre,date,composer,performer,disc,comment,mood"

zeroconf_enabled "no"
filesystem_charset "UTF-8"

audio_output {
  type "httpd"
  name "mpd slowbro http stream"
  encoder "vorbis"
  port "8000"
  bind_to_address "0.0.0.0"
  bitrate "320"
  max_clients "0"
  always_on "yes"
  tags "yes"
}

