version: 5
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
  user: zigbee2mqtt
  password: $MOSQUITTO_ZIGBEE2MQTT_PASSWORD
serial:
  adapter: zstack
  port: /dev/ttyACM0
advanced:
  log_level: info
  log_output:
    - console
  enable_external_js: false
frontend:
  enabled: true
  port: 8080
homeassistant:
  enabled: false
onboarding: false
devices:
  '0xa4c138ee43bc62da':
    friendly_name: climate/main bedroom 0
    humidity_calibration: 4
