version: 5
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
  user: zigbee2mqtt
  password: $MOSQUITTO_ZIGBEE2MQTT_PASSWORD
serial:
  adapter: zstack
  port: /dev/ttyACM0
advanced:
  log_level: info
  log_output:
    - console
  enable_external_js: true
frontend:
  enabled: false
  port: 8080
homeassistant:
  enabled: false
onboarding: false
