vim.pack.add({
  -- Colourscheme
  'https://github.com/EdenEast/nightfox.nvim',

  -- Language server configurations
  'https://github.com/neovim/nvim-lspconfig',

  -- Tree sitter grammars for syntax highlighting
  'https://github.com/nvim-treesitter/nvim-treesitter',

  -- Lots of nice little plugins!
  'https://github.com/nvim-mini/mini.nvim',

   -- Detect tabstop and shiftwidth automatically
  'https://github.com/NMAC427/guess-indent.nvim',

  -- Adds git related signs to the gutter
  'https://github.com/lewis6991/gitsigns.nvim',

  -- Notification and progress UI
  'https://github.com/j-hui/fidget.nvim',
})

vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- Colourscheme and styling
require("nightfox").setup()
require('mini.icons').setup()
require("mini.statusline").setup({ use_icons = vim.g.have_nerd_font })
vim.cmd.colorscheme("duskfox")

-- Auto-close parens, etc
require("mini.pairs").setup()

-- Show buffers as tabs
require("mini.tabline").setup()

-- require("lazy").setup({
--   { -- Fuzzy Finder (files, lsp, etc)
--     "nvim-telescope/telescope.nvim",
--     event = "VimEnter",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
--       { "nvim-telescope/telescope-ui-select.nvim" },
--       { "nvim-tree/nvim-web-devicons",              enabled = vim.g.have_nerd_font },
--     },
--     config = function()
--       require("telescope").setup({
--         extensions = {
--           ["ui-select"] = {
--             require("telescope.themes").get_dropdown(),
--           },
--         },
--       })
--
--       -- Enable Telescope extensions if they are installed
--       pcall(require("telescope").load_extension, "fzf")
--       pcall(require("telescope").load_extension, "ui-select")
--
--       -- See `:help telescope.builtin`
--       local builtin = require("telescope.builtin")
--       vim.keymap.set("n", "<leader><leader>", builtin.find_files, { desc = "Files" })
--       vim.keymap.set("n", "<leader>sh", builtin.help_tags, { desc = "Help" })
--       vim.keymap.set("n", "<leader>sk", builtin.keymaps, { desc = "Keymaps" })
--       vim.keymap.set("n", "<leader>ss", builtin.builtin, { desc = "Telescopes" })
--       vim.keymap.set("n", "<leader>sw", builtin.grep_string, { desc = "Grep current word" })
--       vim.keymap.set("n", "<leader>sg", builtin.live_grep, { desc = "Grep" })
--       vim.keymap.set("n", "<leader>sd", builtin.diagnostics, { desc = "Diagnostics" })
--       vim.keymap.set("n", "<leader>sc", builtin.resume, { desc = "Continue previous search" })
--       vim.keymap.set("n", "<leader>sr", builtin.oldfiles, { desc = 'Recent files' })
--       vim.keymap.set("n", "<leader>sb", builtin.buffers, { desc = "Buffers" })
--       vim.keymap.set("n", "<leader>/", builtin.current_buffer_fuzzy_find, { desc = "Search current buffer" })
--
--       -- It's also possible to pass additional configuration options.
--       --  See `:help telescope.builtin.live_grep()` for information about particular keys
--       vim.keymap.set("n", "<leader>s/", function()
--         builtin.live_grep({
--           grep_open_files = true,
--           prompt_title = "Live Grep in Open Files",
--         })
--       end, { desc = "Search in open files" })
--
--       vim.keymap.set("n", "<leader>sn", function()
--         builtin.find_files({ cwd = vim.fn.stdpath("config") })
--       end, { desc = "Search neovim config" })
--     end,
--   },
--
--   -- LSP Plugins
--   {
--     -- Main LSP Configuration
--     "neovim/nvim-lspconfig",
--     dependencies = {
--     },
--     config = function()
--       --  This function gets run when an LSP attaches to a particular buffer.
--       --    That is to say, every time a new file is opened that is associated with
--       --    an lsp (for example, opening `main.rs` is associated with `rust_analyzer`) this
--       --    function will be executed to configure the current buffer
--       vim.api.nvim_create_autocmd("LspAttach", {
--         group = vim.api.nvim_create_augroup("kickstart-lsp-attach", { clear = true }),
--         callback = function(event)
--           -- In this case, we create a function that lets us more easily define mappings specific
--           -- for LSP related items. It sets the mode, buffer and description for us each time.
--           local map = function(keys, func, desc, mode)
--             mode = mode or "n"
--             vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = desc })
--           end
--
--           -- -- Rename the variable under your cursor.
--           -- --  Most Language Servers support renaming across files, etc.
--           map("grn", vim.lsp.buf.rename, "[R]e[n]ame")
--
--           -- -- Execute a code action, usually your cursor needs to be on top of an error
--           -- -- or a suggestion from your LSP for this to activate.
--           map("gra", vim.lsp.buf.code_action, "[G]oto Code [A]ction", { "n", "x" })
--
--           -- Find references for the word under your cursor.
--           map("grr", require("telescope.builtin").lsp_references, "[G]oto [R]eferences")
--
--           -- Jump to the implementation of the word under your cursor.
--           --  Useful when your language has ways of declaring types without an actual implementation.
--           map("gri", require("telescope.builtin").lsp_implementations, "[G]oto [I]mplementation")
--
--           -- Jump to the definition of the word under your cursor.
--           --  This is where a variable was first declared, or where a function is defined, etc.
--           --  To jump back, press <C-t>.
--           map("gd", require("telescope.builtin").lsp_definitions, "[G]oto [D]efinition")
--
--           -- This is not Goto Definition, this is Goto Declaration.
--           -- For example, in C this would take you to the header.
--           map("gD", vim.lsp.buf.declaration, "[G]oto [D]eclaration")
--
--           -- Fuzzy find all the symbols in your current document.
--           --  Symbols are things like variables, functions, types, etc.
--           map("gO", require("telescope.builtin").lsp_document_symbols, "Open Document Symbols")
--
--           -- Fuzzy find all the symbols in your current workspace.
--           --  Similar to document symbols, except searches over your entire project.
--           map("gW", require("telescope.builtin").lsp_dynamic_workspace_symbols, "Open Workspace Symbols")
--
--           -- Jump to the type of the word under your cursor.
--           --  Useful when you're not sure what type a variable is and you want to see
--           --  the definition of its *type*, not where it was *defined*.
--           map("grt", require("telescope.builtin").lsp_type_definitions, "[G]oto [T]ype Definition")
--
--           -- The following two autocommands are used to highlight references of the
--           -- word under your cursor when your cursor rests there for a little while.
--           --    See `:help CursorHold` for information about when this is executed
--           --
--           -- When you move your cursor, the highlights will be cleared (the second autocommand).
--           local client = vim.lsp.get_client_by_id(event.data.client_id)
--           if
--               client
--               and client:supports_method(vim.lsp.protocol.Methods.textDocument_documentHighlight, event.buf)
--           then
--             local highlight_augroup =
--                 vim.api.nvim_create_augroup("kickstart-lsp-highlight", { clear = false })
--             vim.api.nvim_create_autocmd({ "CursorHold", "CursorHoldI" }, {
--               buffer = event.buf,
--               group = highlight_augroup,
--               callback = vim.lsp.buf.document_highlight,
--             })
--
--             vim.api.nvim_create_autocmd({ "CursorMoved", "CursorMovedI" }, {
--               buffer = event.buf,
--               group = highlight_augroup,
--               callback = vim.lsp.buf.clear_references,
--             })
--
--             vim.api.nvim_create_autocmd("LspDetach", {
--               group = vim.api.nvim_create_augroup("kickstart-lsp-detach", { clear = true }),
--               callback = function(event2)
--                 vim.lsp.buf.clear_references()
--                 vim.api.nvim_clear_autocmds({ group = "kickstart-lsp-highlight", buffer = event2.buf })
--               end,
--             })
--           end
--
--           -- The following code creates a keymap to toggle inlay hints in your
--           -- code, if the language server you are using supports them
--           --
--           -- This may be unwanted, since they displace some of your code
--           if
--               client
--               and client:supports_method(vim.lsp.protocol.Methods.textDocument_inlayHint, event.buf)
--           then
--             map("<leader>th", function()
--               vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = event.buf }))
--             end, "[T]oggle Inlay [H]ints")
--           end
--         end,
--       })
--
--
--       -- Diagnostic Config
--       -- See :help vim.diagnostic.Opts
--       vim.diagnostic.config({
--         severity_sort = true,
--         float = { border = "rounded", source = "if_many" },
--         underline = { severity = vim.diagnostic.severity.ERROR },
--         signs = vim.g.have_nerd_font and {
--           text = {
--             [vim.diagnostic.severity.ERROR] = "󰅚 ",
--             [vim.diagnostic.severity.WARN] = "󰀪 ",
--             [vim.diagnostic.severity.INFO] = "󰋽 ",
--             [vim.diagnostic.severity.HINT] = "󰌶 ",
--           },
--         } or {},
--         virtual_text = {
--           source = "if_many",
--           current_line = false,
--           spacing = 2,
--           format = function(diagnostic)
--             -- Collapse whitespace
--             local collapsed, _ = diagnostic.message:gsub("%s%s+", "  ")
--             return collapsed
--           end,
--         },
--       })
--     end,
--   },
--
--   { -- Autoformat
--     "stevearc/conform.nvim",
--     event = { "BufWritePre" },
--     cmd = { "ConformInfo" },
--     keys = {
--       {
--         "<leader>f",
--         function()
--           require("conform").format({ async = true, lsp_format = "fallback" })
--         end,
--         mode = "",
--         desc = "[F]ormat buffer",
--       },
--     },
--     opts = {
--       notify_on_error = false,
--       format_on_save = function(bufnr)
--         -- Disable "format_on_save lsp_fallback" for languages that don't
--         -- have a well standardized coding style. You can add additional
--         -- languages here or re-enable it for the disabled ones.
--         local disable_filetypes = { c = true, cpp = true }
--         if disable_filetypes[vim.bo[bufnr].filetype] then
--           return nil
--         else
--           return {
--             timeout_ms = 500,
--             lsp_format = "fallback",
--           }
--         end
--       end,
--       formatters_by_ft = {
--         gleam = { lsp_format = "fallback" },
--         javascript = { "prettier" },
--         lua = { "stylua" },
--
--         djot = { "trim_whitespace" },
--         markdown = { "trim_whitespace" },
--         html = { "trim_whitespace" },
--       },
--     },
--   },
--
--   -- Highlight todo, notes, etc in comments
--   {
--     "folke/todo-comments.nvim",
--     event = "VimEnter",
--     dependencies = { "nvim-lua/plenary.nvim" },
--     opts = { signs = false },
--   },
--
--   { -- Collection of various small independent plugins/modules
--     "echasnovski/mini.nvim",
--     config = function()
--       -- Better Around/Inside textobjects
--       --
--       -- Examples:
--       --  - va)  - [V]isually select [A]round [)]paren
--       --  - yinq - [Y]ank [I]nside [N]ext [Q]uote
--       --  - ci'  - [C]hange [I]nside [']quote
--       require("mini.ai").setup({ n_lines = 500 })
--
--       -- Add/delete/replace surroundings (brackets, quotes, etc.)
--       --
--       -- - saiw) - [S]urround [A]dd [I]nner [W]ord [)]Paren
--       -- - sd'   - [S]urround [D]elete [']quotes
--       -- - sr)'  - [S]urround [R]eplace [)] [']
--       require("mini.surround").setup()
--     end,
--   },
