baseurl: ""
url: "https://lpil.uk/"

markdown: kramdown

permalink: "/blog/:title/"

include:
  - .well-known

plugins:
  - jekyll-redirect-from
  - jekyll-feed

whitelist:
  - jekyll-redirect-from
  - jekyll-feed

defaults:
  -
    scope:
      path: ""      # all files
      type: posts   # limit to posts
    values:
      layout: post
